name: Internal Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  unit-test:
    name: Unit test on ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: -> Decode the keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEY_JKS }}
    - name: -> Relocate the keystore file
      run: cp ${{steps.decode_keystore.outputs.filePath}} android/
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: -> Check the environment
      run: flutter doctor -v
    - name: -> Install dependencies
      run: flutter pub get
    - name: -> Analyze the source code
      run: flutter analyze
    # - name: -> Unit test
    #   run: flutter test
    - name: -> Generate apk file
      env:
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: flutter build apk --release --split-per-abi --no-shrink
    # Upload the artifact
    - name: -> Upload the generated app-armeabi-v7a-release.apk file
      uses: actions/upload-artifact@v2
      with:
        name: app-armeabi-v7a-release.apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    - name: -> Upload the generated app-arm64-v8a-release.apk file
      uses: actions/upload-artifact@v2
      with:
        name: app-arm64-v8a-release.apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    - name: -> Upload the generated app-x86_64-release.apk file
      uses: actions/upload-artifact@v2
      with:
        name: app-x86_64-release.apk
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk