name: Tests Application
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev
  # pull_request:
jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-2019, macos-10.15]
        os: [ubuntu-18.04]
    # runs-on: ubuntu-latest
    # container:
    #   image:  google/dart:latest
    steps:
    # Set up Flutter.
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > keystore.jks
    - run: flutter doctor -v

    # Checkout gallery code and get packages.
    - name: -> Checkout gallery code
      uses: actions/checkout@v2
    - name: -> Get packages
      run: flutter pub get

    # Build the artifact
    - name: Generate apk file
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > keystore.jks
      run: flutter build apk --release
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
